
# travis build file inspired by ithlony

language: cpp
compiler:
  - gcc
  - clang
notifications:
  email:
#    recipients:
#      - one@example.com
#      - other@example.com
    on_success: change # [always|never|change] # default: change
    on_failure: change # [always|never|change] # default: always

before_install:
 - cd $HOME
 - pwd
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - if [ $CXX = "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
 - sudo apt-get update -qq
 - if [ $CXX = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev clang-3.2; fi
 - if [ $GCCVER != "" ]; then sudo apt-get install -qq g++$GCCVER; fi
 - if [ $VALGRIND != "0" ]; then sudo apt-get install -qq valgrind; fi
 - wget https://github.com/ned14/boost-trunk/archive/release/Boost_1_54_0.tar.gz
 - tar zxf Boost_1_54_0.tar.gz
 - mv boost-trunk-release-Boost_1_54_0 $HOME/boost-trunk
 - mv $HOME/andy-thomason/genetics $HOME/boost-trunk/libs/genetics
 - BOOST="$HOME/boost-trunk"
 - BOOST_ROOT="$HOME/boost-trunk"
 - PROJECT_ROOT=`pwd`
 - export BOOST_ROOT
 - export BOOST
 - export PROJECT_ROOT


script:
 - cd $HOME/boost-trunk
 - ./bootstrap.sh
 - cd $HOME/boost-trunk/libs/genetics/test
 - ../../../b2
