
# travis build file inspired by ithlony
sudo: false

language: cpp
compiler:
  - gcc
  - clang
notifications:
  email:
    on_success: change # [always|never|change] # default: change
    on_failure: change # [always|never|change] # default: always

before_install:
 - cd $HOME/build
 - pwd
 - wget https://github.com/ned14/boost-trunk/archive/release/Boost_1_54_0.tar.gz
 - tar zxf Boost_1_54_0.tar.gz
 - mv boost-trunk-release-Boost_1_54_0 boost-trunk
 - ls -l
 - mv andy-thomason/genetics boost-trunk/libs/genetics
 - BOOST="$HOME/build/boost-trunk"
 - BOOST_ROOT="$HOME/boost-trunk"
 - export BOOST_ROOT
 - export BOOST

install:
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - gcc-4.8
     - g++-4.8
     - clang

script:
 - pwd
 - cd $HOME/build/boost-trunk
 - ./bootstrap.sh
 - cd $HOME/build/boost-trunk/libs/genetics/test
 - ../../../b2 toolset=$CC
